### ISSUE TITLE
new column in chartevents for units

### ISSUE THREAD

**Issue by theonesp** [theonesp/p_zero-code#19]
Could we get a list of the unit of each vital so it is stored in the table in the proper column?
https://github.com/theonesp/p_zero-code/blob/9ade69852b61dd9f8bec1b7b41a0e429588652c2/build_p_zero/etl/postgres/chartevents/chartevents.sql#L21

**Comment by xborrat** [comment]
I'd rather insert the unit in the dict table. Once we have the dict I'll do it.

**Comment by theonesp** [comment]
MIMIC includes them in both d_items and chartevents, though. let's Weigh up pros and cons

**Comment by theonesp** [comment]
we decided to exclude units from chartevents, it will be more efficient and OMOP does not use units either.
