### ISSUE TITLE
review if we can remove create r_monitors

### ISSUE THREAD

**Issue by xborrat** [theonesp/p_zero-code#31]

**Comment by theonesp** [comment]
where was this in the repo?

**Comment by xborrat** [comment]
Already solved...


[Update 03_postgres_create_tables.sql](https://github.com/theonesp/p_zero-code/commit/02e48a04d1d34d6c0025f3a048fcd5920eddb7f6)  …
r_monitor creation removed
patient_id to patient_ref
id to phi_id
@[xborrat](https://github.com/theonesp/p_zero-code/commits?author=xborrat)
xborrat committed 6 days ago
Verified
